package dao;

import entity.TpYcclHz;
import entity.TpYcclHzExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TpYcclHzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    int countByExample(TpYcclHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    int deleteByExample(TpYcclHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    int insert(TpYcclHz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    int insertSelective(TpYcclHz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    List<TpYcclHz> selectByExample(TpYcclHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    TpYcclHz selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TpYcclHz record, @Param("example") TpYcclHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TpYcclHz record, @Param("example") TpYcclHzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpYcclHz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpYcclHz record);

    int insertBatchModel(@Param("models") List<TpYcclHz> list);
}