package entity;

import java.util.ArrayList;
import java.util.List;

public class TpYcclHzExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    public TpYcclHzExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUuidIsNull() {
            addCriterion("UUID is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("UUID is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("UUID =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("UUID <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("UUID >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("UUID >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("UUID <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("UUID <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("UUID like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("UUID not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("UUID in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("UUID not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("UUID between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("UUID not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andSsdqIsNull() {
            addCriterion("SSDQ is null");
            return (Criteria) this;
        }

        public Criteria andSsdqIsNotNull() {
            addCriterion("SSDQ is not null");
            return (Criteria) this;
        }

        public Criteria andSsdqEqualTo(String value) {
            addCriterion("SSDQ =", value, "ssdq");
            return (Criteria) this;
        }

        public Criteria andSsdqNotEqualTo(String value) {
            addCriterion("SSDQ <>", value, "ssdq");
            return (Criteria) this;
        }

        public Criteria andSsdqGreaterThan(String value) {
            addCriterion("SSDQ >", value, "ssdq");
            return (Criteria) this;
        }

        public Criteria andSsdqGreaterThanOrEqualTo(String value) {
            addCriterion("SSDQ >=", value, "ssdq");
            return (Criteria) this;
        }

        public Criteria andSsdqLessThan(String value) {
            addCriterion("SSDQ <", value, "ssdq");
            return (Criteria) this;
        }

        public Criteria andSsdqLessThanOrEqualTo(String value) {
            addCriterion("SSDQ <=", value, "ssdq");
            return (Criteria) this;
        }

        public Criteria andSsdqLike(String value) {
            addCriterion("SSDQ like", value, "ssdq");
            return (Criteria) this;
        }

        public Criteria andSsdqNotLike(String value) {
            addCriterion("SSDQ not like", value, "ssdq");
            return (Criteria) this;
        }

        public Criteria andSsdqIn(List<String> values) {
            addCriterion("SSDQ in", values, "ssdq");
            return (Criteria) this;
        }

        public Criteria andSsdqNotIn(List<String> values) {
            addCriterion("SSDQ not in", values, "ssdq");
            return (Criteria) this;
        }

        public Criteria andSsdqBetween(String value1, String value2) {
            addCriterion("SSDQ between", value1, value2, "ssdq");
            return (Criteria) this;
        }

        public Criteria andSsdqNotBetween(String value1, String value2) {
            addCriterion("SSDQ not between", value1, value2, "ssdq");
            return (Criteria) this;
        }

        public Criteria andFwjgmcIsNull() {
            addCriterion("FWJGMC is null");
            return (Criteria) this;
        }

        public Criteria andFwjgmcIsNotNull() {
            addCriterion("FWJGMC is not null");
            return (Criteria) this;
        }

        public Criteria andFwjgmcEqualTo(String value) {
            addCriterion("FWJGMC =", value, "fwjgmc");
            return (Criteria) this;
        }

        public Criteria andFwjgmcNotEqualTo(String value) {
            addCriterion("FWJGMC <>", value, "fwjgmc");
            return (Criteria) this;
        }

        public Criteria andFwjgmcGreaterThan(String value) {
            addCriterion("FWJGMC >", value, "fwjgmc");
            return (Criteria) this;
        }

        public Criteria andFwjgmcGreaterThanOrEqualTo(String value) {
            addCriterion("FWJGMC >=", value, "fwjgmc");
            return (Criteria) this;
        }

        public Criteria andFwjgmcLessThan(String value) {
            addCriterion("FWJGMC <", value, "fwjgmc");
            return (Criteria) this;
        }

        public Criteria andFwjgmcLessThanOrEqualTo(String value) {
            addCriterion("FWJGMC <=", value, "fwjgmc");
            return (Criteria) this;
        }

        public Criteria andFwjgmcLike(String value) {
            addCriterion("FWJGMC like", value, "fwjgmc");
            return (Criteria) this;
        }

        public Criteria andFwjgmcNotLike(String value) {
            addCriterion("FWJGMC not like", value, "fwjgmc");
            return (Criteria) this;
        }

        public Criteria andFwjgmcIn(List<String> values) {
            addCriterion("FWJGMC in", values, "fwjgmc");
            return (Criteria) this;
        }

        public Criteria andFwjgmcNotIn(List<String> values) {
            addCriterion("FWJGMC not in", values, "fwjgmc");
            return (Criteria) this;
        }

        public Criteria andFwjgmcBetween(String value1, String value2) {
            addCriterion("FWJGMC between", value1, value2, "fwjgmc");
            return (Criteria) this;
        }

        public Criteria andFwjgmcNotBetween(String value1, String value2) {
            addCriterion("FWJGMC not between", value1, value2, "fwjgmc");
            return (Criteria) this;
        }

        public Criteria andQymcIsNull() {
            addCriterion("QYMC is null");
            return (Criteria) this;
        }

        public Criteria andQymcIsNotNull() {
            addCriterion("QYMC is not null");
            return (Criteria) this;
        }

        public Criteria andQymcEqualTo(String value) {
            addCriterion("QYMC =", value, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcNotEqualTo(String value) {
            addCriterion("QYMC <>", value, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcGreaterThan(String value) {
            addCriterion("QYMC >", value, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcGreaterThanOrEqualTo(String value) {
            addCriterion("QYMC >=", value, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcLessThan(String value) {
            addCriterion("QYMC <", value, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcLessThanOrEqualTo(String value) {
            addCriterion("QYMC <=", value, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcLike(String value) {
            addCriterion("QYMC like", value, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcNotLike(String value) {
            addCriterion("QYMC not like", value, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcIn(List<String> values) {
            addCriterion("QYMC in", values, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcNotIn(List<String> values) {
            addCriterion("QYMC not in", values, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcBetween(String value1, String value2) {
            addCriterion("QYMC between", value1, value2, "qymc");
            return (Criteria) this;
        }

        public Criteria andQymcNotBetween(String value1, String value2) {
            addCriterion("QYMC not between", value1, value2, "qymc");
            return (Criteria) this;
        }

        public Criteria andDzbdmcIsNull() {
            addCriterion("DZBDMC is null");
            return (Criteria) this;
        }

        public Criteria andDzbdmcIsNotNull() {
            addCriterion("DZBDMC is not null");
            return (Criteria) this;
        }

        public Criteria andDzbdmcEqualTo(String value) {
            addCriterion("DZBDMC =", value, "dzbdmc");
            return (Criteria) this;
        }

        public Criteria andDzbdmcNotEqualTo(String value) {
            addCriterion("DZBDMC <>", value, "dzbdmc");
            return (Criteria) this;
        }

        public Criteria andDzbdmcGreaterThan(String value) {
            addCriterion("DZBDMC >", value, "dzbdmc");
            return (Criteria) this;
        }

        public Criteria andDzbdmcGreaterThanOrEqualTo(String value) {
            addCriterion("DZBDMC >=", value, "dzbdmc");
            return (Criteria) this;
        }

        public Criteria andDzbdmcLessThan(String value) {
            addCriterion("DZBDMC <", value, "dzbdmc");
            return (Criteria) this;
        }

        public Criteria andDzbdmcLessThanOrEqualTo(String value) {
            addCriterion("DZBDMC <=", value, "dzbdmc");
            return (Criteria) this;
        }

        public Criteria andDzbdmcLike(String value) {
            addCriterion("DZBDMC like", value, "dzbdmc");
            return (Criteria) this;
        }

        public Criteria andDzbdmcNotLike(String value) {
            addCriterion("DZBDMC not like", value, "dzbdmc");
            return (Criteria) this;
        }

        public Criteria andDzbdmcIn(List<String> values) {
            addCriterion("DZBDMC in", values, "dzbdmc");
            return (Criteria) this;
        }

        public Criteria andDzbdmcNotIn(List<String> values) {
            addCriterion("DZBDMC not in", values, "dzbdmc");
            return (Criteria) this;
        }

        public Criteria andDzbdmcBetween(String value1, String value2) {
            addCriterion("DZBDMC between", value1, value2, "dzbdmc");
            return (Criteria) this;
        }

        public Criteria andDzbdmcNotBetween(String value1, String value2) {
            addCriterion("DZBDMC not between", value1, value2, "dzbdmc");
            return (Criteria) this;
        }

        public Criteria andSkssqqIsNull() {
            addCriterion("SKSSQQ is null");
            return (Criteria) this;
        }

        public Criteria andSkssqqIsNotNull() {
            addCriterion("SKSSQQ is not null");
            return (Criteria) this;
        }

        public Criteria andSkssqqEqualTo(String value) {
            addCriterion("SKSSQQ =", value, "skssqq");
            return (Criteria) this;
        }

        public Criteria andSkssqqNotEqualTo(String value) {
            addCriterion("SKSSQQ <>", value, "skssqq");
            return (Criteria) this;
        }

        public Criteria andSkssqqGreaterThan(String value) {
            addCriterion("SKSSQQ >", value, "skssqq");
            return (Criteria) this;
        }

        public Criteria andSkssqqGreaterThanOrEqualTo(String value) {
            addCriterion("SKSSQQ >=", value, "skssqq");
            return (Criteria) this;
        }

        public Criteria andSkssqqLessThan(String value) {
            addCriterion("SKSSQQ <", value, "skssqq");
            return (Criteria) this;
        }

        public Criteria andSkssqqLessThanOrEqualTo(String value) {
            addCriterion("SKSSQQ <=", value, "skssqq");
            return (Criteria) this;
        }

        public Criteria andSkssqqLike(String value) {
            addCriterion("SKSSQQ like", value, "skssqq");
            return (Criteria) this;
        }

        public Criteria andSkssqqNotLike(String value) {
            addCriterion("SKSSQQ not like", value, "skssqq");
            return (Criteria) this;
        }

        public Criteria andSkssqqIn(List<String> values) {
            addCriterion("SKSSQQ in", values, "skssqq");
            return (Criteria) this;
        }

        public Criteria andSkssqqNotIn(List<String> values) {
            addCriterion("SKSSQQ not in", values, "skssqq");
            return (Criteria) this;
        }

        public Criteria andSkssqqBetween(String value1, String value2) {
            addCriterion("SKSSQQ between", value1, value2, "skssqq");
            return (Criteria) this;
        }

        public Criteria andSkssqqNotBetween(String value1, String value2) {
            addCriterion("SKSSQQ not between", value1, value2, "skssqq");
            return (Criteria) this;
        }

        public Criteria andSkssqzIsNull() {
            addCriterion("SKSSQZ is null");
            return (Criteria) this;
        }

        public Criteria andSkssqzIsNotNull() {
            addCriterion("SKSSQZ is not null");
            return (Criteria) this;
        }

        public Criteria andSkssqzEqualTo(String value) {
            addCriterion("SKSSQZ =", value, "skssqz");
            return (Criteria) this;
        }

        public Criteria andSkssqzNotEqualTo(String value) {
            addCriterion("SKSSQZ <>", value, "skssqz");
            return (Criteria) this;
        }

        public Criteria andSkssqzGreaterThan(String value) {
            addCriterion("SKSSQZ >", value, "skssqz");
            return (Criteria) this;
        }

        public Criteria andSkssqzGreaterThanOrEqualTo(String value) {
            addCriterion("SKSSQZ >=", value, "skssqz");
            return (Criteria) this;
        }

        public Criteria andSkssqzLessThan(String value) {
            addCriterion("SKSSQZ <", value, "skssqz");
            return (Criteria) this;
        }

        public Criteria andSkssqzLessThanOrEqualTo(String value) {
            addCriterion("SKSSQZ <=", value, "skssqz");
            return (Criteria) this;
        }

        public Criteria andSkssqzLike(String value) {
            addCriterion("SKSSQZ like", value, "skssqz");
            return (Criteria) this;
        }

        public Criteria andSkssqzNotLike(String value) {
            addCriterion("SKSSQZ not like", value, "skssqz");
            return (Criteria) this;
        }

        public Criteria andSkssqzIn(List<String> values) {
            addCriterion("SKSSQZ in", values, "skssqz");
            return (Criteria) this;
        }

        public Criteria andSkssqzNotIn(List<String> values) {
            addCriterion("SKSSQZ not in", values, "skssqz");
            return (Criteria) this;
        }

        public Criteria andSkssqzBetween(String value1, String value2) {
            addCriterion("SKSSQZ between", value1, value2, "skssqz");
            return (Criteria) this;
        }

        public Criteria andSkssqzNotBetween(String value1, String value2) {
            addCriterion("SKSSQZ not between", value1, value2, "skssqz");
            return (Criteria) this;
        }

        public Criteria andNsqxIsNull() {
            addCriterion("NSQX is null");
            return (Criteria) this;
        }

        public Criteria andNsqxIsNotNull() {
            addCriterion("NSQX is not null");
            return (Criteria) this;
        }

        public Criteria andNsqxEqualTo(String value) {
            addCriterion("NSQX =", value, "nsqx");
            return (Criteria) this;
        }

        public Criteria andNsqxNotEqualTo(String value) {
            addCriterion("NSQX <>", value, "nsqx");
            return (Criteria) this;
        }

        public Criteria andNsqxGreaterThan(String value) {
            addCriterion("NSQX >", value, "nsqx");
            return (Criteria) this;
        }

        public Criteria andNsqxGreaterThanOrEqualTo(String value) {
            addCriterion("NSQX >=", value, "nsqx");
            return (Criteria) this;
        }

        public Criteria andNsqxLessThan(String value) {
            addCriterion("NSQX <", value, "nsqx");
            return (Criteria) this;
        }

        public Criteria andNsqxLessThanOrEqualTo(String value) {
            addCriterion("NSQX <=", value, "nsqx");
            return (Criteria) this;
        }

        public Criteria andNsqxLike(String value) {
            addCriterion("NSQX like", value, "nsqx");
            return (Criteria) this;
        }

        public Criteria andNsqxNotLike(String value) {
            addCriterion("NSQX not like", value, "nsqx");
            return (Criteria) this;
        }

        public Criteria andNsqxIn(List<String> values) {
            addCriterion("NSQX in", values, "nsqx");
            return (Criteria) this;
        }

        public Criteria andNsqxNotIn(List<String> values) {
            addCriterion("NSQX not in", values, "nsqx");
            return (Criteria) this;
        }

        public Criteria andNsqxBetween(String value1, String value2) {
            addCriterion("NSQX between", value1, value2, "nsqx");
            return (Criteria) this;
        }

        public Criteria andNsqxNotBetween(String value1, String value2) {
            addCriterion("NSQX not between", value1, value2, "nsqx");
            return (Criteria) this;
        }

        public Criteria andSbyyIsNull() {
            addCriterion("SBYY is null");
            return (Criteria) this;
        }

        public Criteria andSbyyIsNotNull() {
            addCriterion("SBYY is not null");
            return (Criteria) this;
        }

        public Criteria andSbyyEqualTo(String value) {
            addCriterion("SBYY =", value, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyNotEqualTo(String value) {
            addCriterion("SBYY <>", value, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyGreaterThan(String value) {
            addCriterion("SBYY >", value, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyGreaterThanOrEqualTo(String value) {
            addCriterion("SBYY >=", value, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyLessThan(String value) {
            addCriterion("SBYY <", value, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyLessThanOrEqualTo(String value) {
            addCriterion("SBYY <=", value, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyLike(String value) {
            addCriterion("SBYY like", value, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyNotLike(String value) {
            addCriterion("SBYY not like", value, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyIn(List<String> values) {
            addCriterion("SBYY in", values, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyNotIn(List<String> values) {
            addCriterion("SBYY not in", values, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyBetween(String value1, String value2) {
            addCriterion("SBYY between", value1, value2, "sbyy");
            return (Criteria) this;
        }

        public Criteria andSbyyNotBetween(String value1, String value2) {
            addCriterion("SBYY not between", value1, value2, "sbyy");
            return (Criteria) this;
        }

        public Criteria andClfsIsNull() {
            addCriterion("CLFS is null");
            return (Criteria) this;
        }

        public Criteria andClfsIsNotNull() {
            addCriterion("CLFS is not null");
            return (Criteria) this;
        }

        public Criteria andClfsEqualTo(String value) {
            addCriterion("CLFS =", value, "clfs");
            return (Criteria) this;
        }

        public Criteria andClfsNotEqualTo(String value) {
            addCriterion("CLFS <>", value, "clfs");
            return (Criteria) this;
        }

        public Criteria andClfsGreaterThan(String value) {
            addCriterion("CLFS >", value, "clfs");
            return (Criteria) this;
        }

        public Criteria andClfsGreaterThanOrEqualTo(String value) {
            addCriterion("CLFS >=", value, "clfs");
            return (Criteria) this;
        }

        public Criteria andClfsLessThan(String value) {
            addCriterion("CLFS <", value, "clfs");
            return (Criteria) this;
        }

        public Criteria andClfsLessThanOrEqualTo(String value) {
            addCriterion("CLFS <=", value, "clfs");
            return (Criteria) this;
        }

        public Criteria andClfsLike(String value) {
            addCriterion("CLFS like", value, "clfs");
            return (Criteria) this;
        }

        public Criteria andClfsNotLike(String value) {
            addCriterion("CLFS not like", value, "clfs");
            return (Criteria) this;
        }

        public Criteria andClfsIn(List<String> values) {
            addCriterion("CLFS in", values, "clfs");
            return (Criteria) this;
        }

        public Criteria andClfsNotIn(List<String> values) {
            addCriterion("CLFS not in", values, "clfs");
            return (Criteria) this;
        }

        public Criteria andClfsBetween(String value1, String value2) {
            addCriterion("CLFS between", value1, value2, "clfs");
            return (Criteria) this;
        }

        public Criteria andClfsNotBetween(String value1, String value2) {
            addCriterion("CLFS not between", value1, value2, "clfs");
            return (Criteria) this;
        }

        public Criteria andCljgIsNull() {
            addCriterion("CLJG is null");
            return (Criteria) this;
        }

        public Criteria andCljgIsNotNull() {
            addCriterion("CLJG is not null");
            return (Criteria) this;
        }

        public Criteria andCljgEqualTo(String value) {
            addCriterion("CLJG =", value, "cljg");
            return (Criteria) this;
        }

        public Criteria andCljgNotEqualTo(String value) {
            addCriterion("CLJG <>", value, "cljg");
            return (Criteria) this;
        }

        public Criteria andCljgGreaterThan(String value) {
            addCriterion("CLJG >", value, "cljg");
            return (Criteria) this;
        }

        public Criteria andCljgGreaterThanOrEqualTo(String value) {
            addCriterion("CLJG >=", value, "cljg");
            return (Criteria) this;
        }

        public Criteria andCljgLessThan(String value) {
            addCriterion("CLJG <", value, "cljg");
            return (Criteria) this;
        }

        public Criteria andCljgLessThanOrEqualTo(String value) {
            addCriterion("CLJG <=", value, "cljg");
            return (Criteria) this;
        }

        public Criteria andCljgLike(String value) {
            addCriterion("CLJG like", value, "cljg");
            return (Criteria) this;
        }

        public Criteria andCljgNotLike(String value) {
            addCriterion("CLJG not like", value, "cljg");
            return (Criteria) this;
        }

        public Criteria andCljgIn(List<String> values) {
            addCriterion("CLJG in", values, "cljg");
            return (Criteria) this;
        }

        public Criteria andCljgNotIn(List<String> values) {
            addCriterion("CLJG not in", values, "cljg");
            return (Criteria) this;
        }

        public Criteria andCljgBetween(String value1, String value2) {
            addCriterion("CLJG between", value1, value2, "cljg");
            return (Criteria) this;
        }

        public Criteria andCljgNotBetween(String value1, String value2) {
            addCriterion("CLJG not between", value1, value2, "cljg");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("BZ is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("BZ is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("BZ =", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("BZ <>", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("BZ >", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("BZ >=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("BZ <", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("BZ <=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("BZ like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("BZ not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("BZ in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("BZ not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("BZ between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("BZ not between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andYclxIsNull() {
            addCriterion("YCLX is null");
            return (Criteria) this;
        }

        public Criteria andYclxIsNotNull() {
            addCriterion("YCLX is not null");
            return (Criteria) this;
        }

        public Criteria andYclxEqualTo(String value) {
            addCriterion("YCLX =", value, "yclx");
            return (Criteria) this;
        }

        public Criteria andYclxNotEqualTo(String value) {
            addCriterion("YCLX <>", value, "yclx");
            return (Criteria) this;
        }

        public Criteria andYclxGreaterThan(String value) {
            addCriterion("YCLX >", value, "yclx");
            return (Criteria) this;
        }

        public Criteria andYclxGreaterThanOrEqualTo(String value) {
            addCriterion("YCLX >=", value, "yclx");
            return (Criteria) this;
        }

        public Criteria andYclxLessThan(String value) {
            addCriterion("YCLX <", value, "yclx");
            return (Criteria) this;
        }

        public Criteria andYclxLessThanOrEqualTo(String value) {
            addCriterion("YCLX <=", value, "yclx");
            return (Criteria) this;
        }

        public Criteria andYclxLike(String value) {
            addCriterion("YCLX like", value, "yclx");
            return (Criteria) this;
        }

        public Criteria andYclxNotLike(String value) {
            addCriterion("YCLX not like", value, "yclx");
            return (Criteria) this;
        }

        public Criteria andYclxIn(List<String> values) {
            addCriterion("YCLX in", values, "yclx");
            return (Criteria) this;
        }

        public Criteria andYclxNotIn(List<String> values) {
            addCriterion("YCLX not in", values, "yclx");
            return (Criteria) this;
        }

        public Criteria andYclxBetween(String value1, String value2) {
            addCriterion("YCLX between", value1, value2, "yclx");
            return (Criteria) this;
        }

        public Criteria andYclxNotBetween(String value1, String value2) {
            addCriterion("YCLX not between", value1, value2, "yclx");
            return (Criteria) this;
        }

        public Criteria andYxbzIsNull() {
            addCriterion("YXBZ is null");
            return (Criteria) this;
        }

        public Criteria andYxbzIsNotNull() {
            addCriterion("YXBZ is not null");
            return (Criteria) this;
        }

        public Criteria andYxbzEqualTo(String value) {
            addCriterion("YXBZ =", value, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzNotEqualTo(String value) {
            addCriterion("YXBZ <>", value, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzGreaterThan(String value) {
            addCriterion("YXBZ >", value, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzGreaterThanOrEqualTo(String value) {
            addCriterion("YXBZ >=", value, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzLessThan(String value) {
            addCriterion("YXBZ <", value, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzLessThanOrEqualTo(String value) {
            addCriterion("YXBZ <=", value, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzLike(String value) {
            addCriterion("YXBZ like", value, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzNotLike(String value) {
            addCriterion("YXBZ not like", value, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzIn(List<String> values) {
            addCriterion("YXBZ in", values, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzNotIn(List<String> values) {
            addCriterion("YXBZ not in", values, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzBetween(String value1, String value2) {
            addCriterion("YXBZ between", value1, value2, "yxbz");
            return (Criteria) this;
        }

        public Criteria andYxbzNotBetween(String value1, String value2) {
            addCriterion("YXBZ not between", value1, value2, "yxbz");
            return (Criteria) this;
        }

        public Criteria andSsnfIsNull() {
            addCriterion("SSNF is null");
            return (Criteria) this;
        }

        public Criteria andSsnfIsNotNull() {
            addCriterion("SSNF is not null");
            return (Criteria) this;
        }

        public Criteria andSsnfEqualTo(Integer value) {
            addCriterion("SSNF =", value, "ssnf");
            return (Criteria) this;
        }

        public Criteria andSsnfNotEqualTo(Integer value) {
            addCriterion("SSNF <>", value, "ssnf");
            return (Criteria) this;
        }

        public Criteria andSsnfGreaterThan(Integer value) {
            addCriterion("SSNF >", value, "ssnf");
            return (Criteria) this;
        }

        public Criteria andSsnfGreaterThanOrEqualTo(Integer value) {
            addCriterion("SSNF >=", value, "ssnf");
            return (Criteria) this;
        }

        public Criteria andSsnfLessThan(Integer value) {
            addCriterion("SSNF <", value, "ssnf");
            return (Criteria) this;
        }

        public Criteria andSsnfLessThanOrEqualTo(Integer value) {
            addCriterion("SSNF <=", value, "ssnf");
            return (Criteria) this;
        }

        public Criteria andSsnfIn(List<Integer> values) {
            addCriterion("SSNF in", values, "ssnf");
            return (Criteria) this;
        }

        public Criteria andSsnfNotIn(List<Integer> values) {
            addCriterion("SSNF not in", values, "ssnf");
            return (Criteria) this;
        }

        public Criteria andSsnfBetween(Integer value1, Integer value2) {
            addCriterion("SSNF between", value1, value2, "ssnf");
            return (Criteria) this;
        }

        public Criteria andSsnfNotBetween(Integer value1, Integer value2) {
            addCriterion("SSNF not between", value1, value2, "ssnf");
            return (Criteria) this;
        }

        public Criteria andSsyfIsNull() {
            addCriterion("SSYF is null");
            return (Criteria) this;
        }

        public Criteria andSsyfIsNotNull() {
            addCriterion("SSYF is not null");
            return (Criteria) this;
        }

        public Criteria andSsyfEqualTo(Integer value) {
            addCriterion("SSYF =", value, "ssyf");
            return (Criteria) this;
        }

        public Criteria andSsyfNotEqualTo(Integer value) {
            addCriterion("SSYF <>", value, "ssyf");
            return (Criteria) this;
        }

        public Criteria andSsyfGreaterThan(Integer value) {
            addCriterion("SSYF >", value, "ssyf");
            return (Criteria) this;
        }

        public Criteria andSsyfGreaterThanOrEqualTo(Integer value) {
            addCriterion("SSYF >=", value, "ssyf");
            return (Criteria) this;
        }

        public Criteria andSsyfLessThan(Integer value) {
            addCriterion("SSYF <", value, "ssyf");
            return (Criteria) this;
        }

        public Criteria andSsyfLessThanOrEqualTo(Integer value) {
            addCriterion("SSYF <=", value, "ssyf");
            return (Criteria) this;
        }

        public Criteria andSsyfIn(List<Integer> values) {
            addCriterion("SSYF in", values, "ssyf");
            return (Criteria) this;
        }

        public Criteria andSsyfNotIn(List<Integer> values) {
            addCriterion("SSYF not in", values, "ssyf");
            return (Criteria) this;
        }

        public Criteria andSsyfBetween(Integer value1, Integer value2) {
            addCriterion("SSYF between", value1, value2, "ssyf");
            return (Criteria) this;
        }

        public Criteria andSsyfNotBetween(Integer value1, Integer value2) {
            addCriterion("SSYF not between", value1, value2, "ssyf");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tp_yccl_hz
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}