package entity;

import java.util.Date;

public class TpYcclHz {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_yccl_hz.UUID
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_yccl_hz.SSDQ
     *
     * @mbggenerated
     */
    private String ssdq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_yccl_hz.FWJGMC
     *
     * @mbggenerated
     */
    private String fwjgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_yccl_hz.QYMC
     *
     * @mbggenerated
     */
    private String qymc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_yccl_hz.DZBDMC
     *
     * @mbggenerated
     */
    private String dzbdmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_yccl_hz.SKSSQQ
     *
     * @mbggenerated
     */
    private String skssqq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_yccl_hz.SKSSQZ
     *
     * @mbggenerated
     */
    private String skssqz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_yccl_hz.NSQX
     *
     * @mbggenerated
     */
    private String nsqx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_yccl_hz.SBYY
     *
     * @mbggenerated
     */
    private String sbyy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_yccl_hz.CLFS
     *
     * @mbggenerated
     */
    private String clfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_yccl_hz.CLJG
     *
     * @mbggenerated
     */
    private String cljg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_yccl_hz.BZ
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_yccl_hz.YCLX
     *
     * @mbggenerated
     */
    private String yclx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_yccl_hz.YXBZ
     *
     * @mbggenerated
     */
    private String yxbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_yccl_hz.SSNF
     *
     * @mbggenerated
     */
    private Integer ssnf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_yccl_hz.SSYF
     *
     * @mbggenerated
     */
    private Integer ssyf;

    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_yccl_hz.UUID
     *
     * @return the value of tp_yccl_hz.UUID
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_yccl_hz.UUID
     *
     * @param uuid the value for tp_yccl_hz.UUID
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_yccl_hz.SSDQ
     *
     * @return the value of tp_yccl_hz.SSDQ
     *
     * @mbggenerated
     */
    public String getSsdq() {
        return ssdq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_yccl_hz.SSDQ
     *
     * @param ssdq the value for tp_yccl_hz.SSDQ
     *
     * @mbggenerated
     */
    public void setSsdq(String ssdq) {
        this.ssdq = ssdq == null ? null : ssdq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_yccl_hz.FWJGMC
     *
     * @return the value of tp_yccl_hz.FWJGMC
     *
     * @mbggenerated
     */
    public String getFwjgmc() {
        return fwjgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_yccl_hz.FWJGMC
     *
     * @param fwjgmc the value for tp_yccl_hz.FWJGMC
     *
     * @mbggenerated
     */
    public void setFwjgmc(String fwjgmc) {
        this.fwjgmc = fwjgmc == null ? null : fwjgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_yccl_hz.QYMC
     *
     * @return the value of tp_yccl_hz.QYMC
     *
     * @mbggenerated
     */
    public String getQymc() {
        return qymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_yccl_hz.QYMC
     *
     * @param qymc the value for tp_yccl_hz.QYMC
     *
     * @mbggenerated
     */
    public void setQymc(String qymc) {
        this.qymc = qymc == null ? null : qymc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_yccl_hz.DZBDMC
     *
     * @return the value of tp_yccl_hz.DZBDMC
     *
     * @mbggenerated
     */
    public String getDzbdmc() {
        return dzbdmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_yccl_hz.DZBDMC
     *
     * @param dzbdmc the value for tp_yccl_hz.DZBDMC
     *
     * @mbggenerated
     */
    public void setDzbdmc(String dzbdmc) {
        this.dzbdmc = dzbdmc == null ? null : dzbdmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_yccl_hz.SKSSQQ
     *
     * @return the value of tp_yccl_hz.SKSSQQ
     *
     * @mbggenerated
     */
    public String getSkssqq() {
        return skssqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_yccl_hz.SKSSQQ
     *
     * @param skssqq the value for tp_yccl_hz.SKSSQQ
     *
     * @mbggenerated
     */
    public void setSkssqq(String skssqq) {
        this.skssqq = skssqq == null ? null : skssqq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_yccl_hz.SKSSQZ
     *
     * @return the value of tp_yccl_hz.SKSSQZ
     *
     * @mbggenerated
     */
    public String getSkssqz() {
        return skssqz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_yccl_hz.SKSSQZ
     *
     * @param skssqz the value for tp_yccl_hz.SKSSQZ
     *
     * @mbggenerated
     */
    public void setSkssqz(String skssqz) {
        this.skssqz = skssqz == null ? null : skssqz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_yccl_hz.NSQX
     *
     * @return the value of tp_yccl_hz.NSQX
     *
     * @mbggenerated
     */
    public String getNsqx() {
        return nsqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_yccl_hz.NSQX
     *
     * @param nsqx the value for tp_yccl_hz.NSQX
     *
     * @mbggenerated
     */
    public void setNsqx(String nsqx) {
        this.nsqx = nsqx == null ? null : nsqx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_yccl_hz.SBYY
     *
     * @return the value of tp_yccl_hz.SBYY
     *
     * @mbggenerated
     */
    public String getSbyy() {
        return sbyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_yccl_hz.SBYY
     *
     * @param sbyy the value for tp_yccl_hz.SBYY
     *
     * @mbggenerated
     */
    public void setSbyy(String sbyy) {
        this.sbyy = sbyy == null ? null : sbyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_yccl_hz.CLFS
     *
     * @return the value of tp_yccl_hz.CLFS
     *
     * @mbggenerated
     */
    public String getClfs() {
        return clfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_yccl_hz.CLFS
     *
     * @param clfs the value for tp_yccl_hz.CLFS
     *
     * @mbggenerated
     */
    public void setClfs(String clfs) {
        this.clfs = clfs == null ? null : clfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_yccl_hz.CLJG
     *
     * @return the value of tp_yccl_hz.CLJG
     *
     * @mbggenerated
     */
    public String getCljg() {
        return cljg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_yccl_hz.CLJG
     *
     * @param cljg the value for tp_yccl_hz.CLJG
     *
     * @mbggenerated
     */
    public void setCljg(String cljg) {
        this.cljg = cljg == null ? null : cljg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_yccl_hz.BZ
     *
     * @return the value of tp_yccl_hz.BZ
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_yccl_hz.BZ
     *
     * @param bz the value for tp_yccl_hz.BZ
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_yccl_hz.YCLX
     *
     * @return the value of tp_yccl_hz.YCLX
     *
     * @mbggenerated
     */
    public String getYclx() {
        return yclx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_yccl_hz.YCLX
     *
     * @param yclx the value for tp_yccl_hz.YCLX
     *
     * @mbggenerated
     */
    public void setYclx(String yclx) {
        this.yclx = yclx == null ? null : yclx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_yccl_hz.YXBZ
     *
     * @return the value of tp_yccl_hz.YXBZ
     *
     * @mbggenerated
     */
    public String getYxbz() {
        return yxbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_yccl_hz.YXBZ
     *
     * @param yxbz the value for tp_yccl_hz.YXBZ
     *
     * @mbggenerated
     */
    public void setYxbz(String yxbz) {
        this.yxbz = yxbz == null ? null : yxbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_yccl_hz.SSNF
     *
     * @return the value of tp_yccl_hz.SSNF
     *
     * @mbggenerated
     */
    public Integer getSsnf() {
        return ssnf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_yccl_hz.SSNF
     *
     * @param ssnf the value for tp_yccl_hz.SSNF
     *
     * @mbggenerated
     */
    public void setSsnf(Integer ssnf) {
        this.ssnf = ssnf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_yccl_hz.SSYF
     *
     * @return the value of tp_yccl_hz.SSYF
     *
     * @mbggenerated
     */
    public Integer getSsyf() {
        return ssyf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_yccl_hz.SSYF
     *
     * @param ssyf the value for tp_yccl_hz.SSYF
     *
     * @mbggenerated
     */
    public void setSsyf(Integer ssyf) {
        this.ssyf = ssyf;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}